In [1]:
import numpy as np

In [2]:
# Question a
np.random.seed(0)
a=np.random.randint(11, size=(3,12, 10))
print(a, '\n\n', a.shape)

[[[ 5  0  3  3  7  9  3  5  2  4]
  [ 7  6  8  8 10  1  6  7  7  8]
  [ 1  5  9  8  9  4  3  0  3  5]
  [ 0  2  3  8  1  3  3  3  7  0]
  [ 1  9  9  0 10  4  7  3  2  7]
  [ 2  0  0  4  5  5  6  8  4  1]
  [ 4  9 10 10  8  1  1  7  9  9]
  [ 3  6  7  2  0  3  5  9 10  4]
  [ 4  6  4  4  3  4  4  8  4  3]
  [10  7  5  5  0  1  5  9  3  0]
  [ 5  0  1  2  4  2  0  3  2 10]
  [ 0  7  5  9  0 10  2 10  7  2]]

 [[ 9  2  3  3  2  3  4  1  2  9]
  [10  1  4 10  6  8  2  3  0  0]
  [ 6  0  6  3 10  3  8  8  8  2]
  [ 3  2  0  8  8  3  8 10  2  8]
  [ 4  3  0  4  3  6  9  8  0  8]
  [ 5  9  0  9  6  5  3  1  8  0]
  [ 4  9  6  5  7  8  8  9  2  8]
  [ 6  6  9  1  6  8  8  3  2  3]
  [10  6  3  6  5  7  0  8  4 10]
  [ 6  5  8  2  3  9  7  5  3  4]
  [ 5  3  3  7  9  9  9  7  3 10]
  [ 2  3  9 10  7  7  5  1  2  2]]

 [[ 8  1  5  8  4  0  2  5  5  0]
  [ 8  1  1  0  3  8  8  4  4  0]
  [ 9  3  7  3  2  1  1  2  1  4]
  [ 2  5  5  5  2  5  7  7  6  1]
  [ 6  7  2  3  1  9  5  9  9  2]
  [ 0  9  

In [3]:
# Question b
b = a[:,2:-2, 1:-1]
print(b, '\n\n',b.shape)

[[[ 5  9  8  9  4  3  0  3]
  [ 2  3  8  1  3  3  3  7]
  [ 9  9  0 10  4  7  3  2]
  [ 0  0  4  5  5  6  8  4]
  [ 9 10 10  8  1  1  7  9]
  [ 6  7  2  0  3  5  9 10]
  [ 6  4  4  3  4  4  8  4]
  [ 7  5  5  0  1  5  9  3]]

 [[ 0  6  3 10  3  8  8  8]
  [ 2  0  8  8  3  8 10  2]
  [ 3  0  4  3  6  9  8  0]
  [ 9  0  9  6  5  3  1  8]
  [ 9  6  5  7  8  8  9  2]
  [ 6  9  1  6  8  8  3  2]
  [ 6  3  6  5  7  0  8  4]
  [ 5  8  2  3  9  7  5  3]]

 [[ 3  7  3  2  1  1  2  1]
  [ 5  5  5  2  5  7  7  6]
  [ 7  2  3  1  9  5  9  9]
  [ 9  1  9 10  0  6  0 10]
  [ 4  3  3  8  8  7  0  3]
  [ 7 10  1  8  4  7  0  4]
  [10  6  4  2  4  6  3 10]
  [ 8  5  0  8  5  4  7 10]]] 

 (3, 8, 8)


In [4]:
# Question c
c = np.sum(b, axis = 1)
print(c,'\n\n', c.shape)

[[44 47 41 36 25 34 47 42]
 [40 32 38 48 49 51 52 29]
 [53 39 28 41 36 43 28 53]] 

 (3, 8)


In [5]:
# Question d
d = np.ndarray.flatten(b)
print(d,'\n\n',d.shape)

[ 5  9  8  9  4  3  0  3  2  3  8  1  3  3  3  7  9  9  0 10  4  7  3  2
  0  0  4  5  5  6  8  4  9 10 10  8  1  1  7  9  6  7  2  0  3  5  9 10
  6  4  4  3  4  4  8  4  7  5  5  0  1  5  9  3  0  6  3 10  3  8  8  8
  2  0  8  8  3  8 10  2  3  0  4  3  6  9  8  0  9  0  9  6  5  3  1  8
  9  6  5  7  8  8  9  2  6  9  1  6  8  8  3  2  6  3  6  5  7  0  8  4
  5  8  2  3  9  7  5  3  3  7  3  2  1  1  2  1  5  5  5  2  5  7  7  6
  7  2  3  1  9  5  9  9  9  1  9 10  0  6  0 10  4  3  3  8  8  7  0  3
  7 10  1  8  4  7  0  4 10  6  4  2  4  6  3 10  8  5  0  8  5  4  7 10] 

 (192,)


In [6]:
# Question e
np.random.seed(0)
e=np.random.randint(11, size=(1000,1000)) ; f=np.random.randint(11, size=(1000,1000))

def matmul(in1, in2):
    out = np.zeros(in1.shape)
    for i in range(in1.shape[0]):
        for j in range(in2.shape[1]):
            out[i,j] = np.dot(in1[i,:], in2[:,j])
    return out

import time

t = time.time()
g = matmul(e,f)
print('For self-defined', np.round_(time.time() - t, 10), 'sec elapsed')

t1 = time.time()
g = e@f
print('For inbuilt function', np.round_(time.time() - t1, 10), 'sec elapsed')

For self-defined 7.1191501617 sec elapsed
For inbuilt function 4.4536879063 sec elapsed


The inbuilt function is around 1.5x faster for the given matrix size. @ basically calls the inbuilt 'matmul' operator whereas the self-defined function here calls the 'dot' operator. Numpy documentation recommends using matmul since it is optimised for arrays of larger size.